{
 "title": "Dashboard_1",
 "time": { "from": "2021-03-12T00:00:00.000Z", "to": "2021-03-18T00:00:00.000Z" },
 "panels": [
  {
   "title": "Variation du DAX sur la période",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  Indice AS metric,\n  Variation\nFROM cours\nWHERE\n  Indice = 'DAX '\nORDER BY date"
    }
   ]
  },
  {
   "title": "Variation des Indice boursiers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  Indice AS metric,\n  Variation\nFROM cours\nORDER BY date"
    }
   ]
  },
  {
   "title": "Valeur Hautes et basse pour les indices bourciers",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  Indice AS metric,\n  Bas,\n  Haut\nFROM cours\nORDER BY date"
    }
   ]
  },
  {
   "title": "LEs volume pour le CAC 40 sur la période",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  Indice AS metric,\n  Volume\nFROM cours\nWHERE\n  Indice = 'CAC 40 '\nORDER BY date"
    }
   ]
  }
 ]
}