version: "2"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: root

  mysql:
    image: mysql:5.7
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boursorama
    volumes:
    - ./data/cours.sql:/docker-entrypoint-initdb.d/cours.sql
    